/* Vocab, part 2. */
window.VOCAB.push(
  { w: 'acquiesce', pos: 'v.', d: 'to accept something reluctantly without protest', ex: 'The council finally acquiesced to the residents\' demands.' },
  { w: 'adept', pos: 'adj.', d: 'very skilled or proficient', ex: 'She is adept at spotting grammar errors.' },
  { w: 'advocate', pos: 'v.', d: 'to publicly support or recommend', ex: 'The report advocates stricter safety rules.' },
  { w: 'alleviate', pos: 'v.', d: 'to make suffering or a problem less severe', ex: 'Medicine alleviated his headache.' },
  { w: 'anachronism', pos: 'n.', d: 'something placed in the wrong historical period', ex: 'A wristwatch in a medieval film is an anachronism.' },
  { w: 'antithesis', pos: 'n.', d: 'the direct opposite', ex: 'Her calm was the antithesis of his panic.' },
  { w: 'articulate', pos: 'v./adj.', d: 'to express clearly; able to express ideas clearly', ex: 'He articulated his concerns at the meeting.' },
  { w: 'assert', pos: 'v.', d: 'to state confidently as true', ex: 'The author asserts that cities need more parks.' },
  { w: 'attenuate', pos: 'v.', d: 'to reduce in force or effect', ex: 'Thick walls attenuate street noise.' },
  { w: 'censure', pos: 'v./n.', d: 'to express strong disapproval; formal criticism', ex: 'The senator was censured for misconduct.' },
  { w: 'conspicuous', pos: 'adj.', d: 'clearly visible; attracting notice', ex: 'A conspicuous red sign marked the exit.' },
  { w: 'contentious', pos: 'adj.', d: 'causing or likely to cause disagreement', ex: 'The new law remains contentious.' },
  { w: 'convoluted', pos: 'adj.', d: 'extremely complex and difficult to follow', ex: 'The instructions were so convoluted that no one understood them.' },
  { w: 'credulous', pos: 'adj.', d: 'too ready to believe things', ex: 'Credulous readers accepted the fake story.' },
  { w: 'delineate', pos: 'v.', d: 'to describe or outline precisely', ex: 'The contract delineates each partner\'s duties.' },
  { w: 'didactic', pos: 'adj.', d: 'intended to teach, often in a moralizing way', ex: 'The fable has a clearly didactic purpose.' },
  { w: 'dissonance', pos: 'n.', d: 'a lack of harmony or agreement', ex: 'There was dissonance between his words and actions.' },
  { w: 'eclectic', pos: 'adj.', d: 'drawing from a wide range of sources', ex: 'Her playlist is wonderfully eclectic.' },
  { w: 'efficacy', pos: 'n.', d: 'the ability to produce a desired result', ex: 'Trials tested the vaccine\'s efficacy.' },
  { w: 'elusive', pos: 'adj.', d: 'difficult to find, catch, or achieve', ex: 'A perfect score felt elusive until test day.' },
  { w: 'entrenched', pos: 'adj.', d: 'firmly established and difficult to change', ex: 'Entrenched habits are hard to break.' },
  { w: 'equivocal', pos: 'adj.', d: 'open to more than one interpretation; ambiguous', ex: 'His equivocal answer satisfied no one.' },
  { w: 'exemplify', pos: 'v.', d: 'to be a typical example of', ex: 'The cathedral exemplifies Gothic design.' },
  { w: 'frugal', pos: 'adj.', d: 'sparing or economical with money', ex: 'A frugal student, he saved most of his wages.' },
  { w: 'galvanize', pos: 'v.', d: 'to shock or excite into action', ex: 'The speech galvanized volunteers.' },
  { w: 'hypothetical', pos: 'adj.', d: 'based on a suggested idea rather than fact', ex: 'Consider a hypothetical situation.' },
  { w: 'idiosyncratic', pos: 'adj.', d: 'peculiar to an individual', ex: 'His idiosyncratic style made his essays memorable.' },
  { w: 'implicit', pos: 'adj.', d: 'suggested though not directly expressed', ex: 'There was an implicit criticism in her praise.' },
  { w: 'indifferent', pos: 'adj.', d: 'having no particular interest or concern', ex: 'He seemed indifferent to the outcome.' },
  { w: 'inherent', pos: 'adj.', d: 'existing as a permanent, essential quality', ex: 'Risk is inherent in any investment.' },
  { w: 'insular', pos: 'adj.', d: 'narrow-minded; isolated from outside influences', ex: 'The insular community distrusted newcomers.' },
  { w: 'lucid', pos: 'adj.', d: 'expressed clearly; easy to understand', ex: 'She gave a lucid explanation of the theory.' },
  { w: 'mundane', pos: 'adj.', d: 'lacking interest or excitement; ordinary', ex: 'The novel turns mundane chores into poetry.' },
  { w: 'nuanced', pos: 'adj.', d: 'characterized by subtle distinctions', ex: 'The essay offers a nuanced view of the debate.' },
  { w: 'ostensibly', pos: 'adv.', d: 'as appears or is stated, but perhaps not actually', ex: 'The trip was ostensibly for business.' },
  { w: 'perfunctory', pos: 'adj.', d: 'carried out with minimal effort', ex: 'He gave a perfunctory wave and left.' },
  { w: 'plausible', pos: 'adj.', d: 'seeming reasonable or probable', ex: 'That is a plausible explanation for the data.' },
  { w: 'reconcile', pos: 'v.', d: 'to make consistent or compatible', ex: 'Scientists tried to reconcile the two theories.' },
  { w: 'rudimentary', pos: 'adj.', d: 'involving only basic principles', ex: 'He had a rudimentary grasp of Spanish.' },
  { w: 'salient', pos: 'adj.', d: 'most noticeable or important', ex: 'The salient point is that costs doubled.' },
  { w: 'tacit', pos: 'adj.', d: 'understood without being stated', ex: 'They had a tacit agreement not to discuss it.' },
  { w: 'ubiquitous', pos: 'adj.', d: 'present or found everywhere', ex: 'Smartphones are now ubiquitous.' }
);
window.VOCAB.sort((a, b) => a.w.localeCompare(b.w));
