/* High-yield vocabulary for SAT Reading & Writing (words in context) and ACT Reading. */
window.VOCAB = [
  { w: 'abate', pos: 'v.', d: 'to become less intense or widespread', ex: 'The storm finally abated after midnight.' },
  { w: 'aberration', pos: 'n.', d: 'a departure from what is normal or expected', ex: 'The low score was an aberration in an otherwise strong record.' },
  { w: 'ambivalent', pos: 'adj.', d: 'having mixed or contradictory feelings', ex: 'She felt ambivalent about moving: excited, but sad to leave.' },
  { w: 'ameliorate', pos: 'v.', d: 'to make something bad better', ex: 'New policies aimed to ameliorate traffic congestion.' },
  { w: 'anomaly', pos: 'n.', d: 'something that deviates from the standard', ex: 'The data point was an anomaly the researchers could not explain.' },
  { w: 'arbitrary', pos: 'adj.', d: 'based on random choice rather than reason', ex: 'The deadline seemed arbitrary to the students.' },
  { w: 'ascertain', pos: 'v.', d: 'to find out for certain', ex: 'Investigators worked to ascertain the cause of the fire.' },
  { w: 'austere', pos: 'adj.', d: 'severely plain; without decoration or comfort', ex: 'The monk lived in an austere stone cell.' },
  { w: 'benevolent', pos: 'adj.', d: 'well-meaning and kindly', ex: 'A benevolent donor funded the new library.' },
  { w: 'bolster', pos: 'v.', d: 'to support or strengthen', ex: 'New evidence bolstered the scientist\'s hypothesis.' },
  { w: 'candid', pos: 'adj.', d: 'truthful and straightforward; frank', ex: 'He gave a candid account of his mistakes.' },
  { w: 'capricious', pos: 'adj.', d: 'given to sudden changes of mood or behavior', ex: 'The capricious weather ruined our picnic plans.' },
  { w: 'circumvent', pos: 'v.', d: 'to find a way around an obstacle or rule', ex: 'They tried to circumvent the rules with a loophole.' },
  { w: 'cogent', pos: 'adj.', d: 'clear, logical, and convincing', ex: 'She made a cogent argument for later school start times.' },
  { w: 'complacent', pos: 'adj.', d: 'uncritically satisfied with oneself', ex: 'After early success, the team grew complacent.' },
  { w: 'concede', pos: 'v.', d: 'to admit that something is true, often reluctantly', ex: 'The author concedes that the data are limited.' },
  { w: 'corroborate', pos: 'v.', d: 'to confirm or give support to a claim', ex: 'Two witnesses corroborated her story.' },
  { w: 'cursory', pos: 'adj.', d: 'hasty and therefore not thorough', ex: 'A cursory glance missed the error.' },
  { w: 'debunk', pos: 'v.', d: 'to expose the falseness of an idea', ex: 'The study debunked a popular myth about memory.' },
  { w: 'deference', pos: 'n.', d: 'humble submission and respect', ex: 'In deference to tradition, they kept the old name.' },
  { w: 'diligent', pos: 'adj.', d: 'showing care and effort in work', ex: 'Diligent practice raised his score by 150 points.' },
  { w: 'discern', pos: 'v.', d: 'to perceive or recognize something', ex: 'It was hard to discern the author\'s true opinion.' },
  { w: 'disparate', pos: 'adj.', d: 'essentially different in kind; not comparable', ex: 'The book weaves together disparate storylines.' },
  { w: 'elucidate', pos: 'v.', d: 'to make clear; explain', ex: 'The diagram elucidates how the engine works.' },
  { w: 'empirical', pos: 'adj.', d: 'based on observation or experiment', ex: 'The claim lacked empirical support.' },
  { w: 'ephemeral', pos: 'adj.', d: 'lasting for a very short time', ex: 'Social media trends are often ephemeral.' },
  { w: 'exacerbate', pos: 'v.', d: 'to make a problem worse', ex: 'Skipping sleep exacerbated her stress.' },
  { w: 'extol', pos: 'v.', d: 'to praise enthusiastically', ex: 'Critics extolled the novel\'s vivid prose.' },
  { w: 'facilitate', pos: 'v.', d: 'to make an action or process easier', ex: 'Shared notes facilitate group study.' },
  { w: 'fortuitous', pos: 'adj.', d: 'happening by chance, often luckily', ex: 'A fortuitous meeting led to a job offer.' },
  { w: 'garner', pos: 'v.', d: 'to gather or collect, especially support', ex: 'The proposal garnered wide support.' },
  { w: 'hinder', pos: 'v.', d: 'to create difficulties that slow progress', ex: 'Poor lighting hindered the search.' },
  { w: 'impartial', pos: 'adj.', d: 'treating all sides equally; fair', ex: 'Judges must remain impartial.' },
  { w: 'impetus', pos: 'n.', d: 'a force that makes something happen', ex: 'The flood was the impetus for new levees.' },
  { w: 'inadvertent', pos: 'adj.', d: 'not resulting from deliberate planning', ex: 'An inadvertent typo changed the meaning.' },
  { w: 'incongruous', pos: 'adj.', d: 'out of place; not in harmony', ex: 'A tuxedo looked incongruous at the beach party.' },
  { w: 'innocuous', pos: 'adj.', d: 'not harmful or offensive', ex: 'The question seemed innocuous but caused an argument.' },
  { w: 'jeopardize', pos: 'v.', d: 'to put at risk', ex: 'Missing practice could jeopardize her spot on the team.' },
  { w: 'lament', pos: 'v.', d: 'to express sorrow or regret', ex: 'The narrator laments the loss of the old town.' },
  { w: 'meticulous', pos: 'adj.', d: 'showing great attention to detail', ex: 'Her meticulous notes made review easy.' },
  { w: 'mitigate', pos: 'v.', d: 'to make less severe', ex: 'Trees can mitigate urban heat.' },
  { w: 'negligible', pos: 'adj.', d: 'so small as to be unimportant', ex: 'The difference in cost was negligible.' },
  { w: 'novel', pos: 'adj.', d: 'new and unusual', ex: 'The team proposed a novel solution.' },
  { w: 'obscure', pos: 'adj./v.', d: 'not well known; or, to hide from view', ex: 'Clouds obscured the summit.' },
  { w: 'paradox', pos: 'n.', d: 'a seemingly contradictory statement that may be true', ex: 'It is a paradox that more choice can make people less happy.' },
  { w: 'pragmatic', pos: 'adj.', d: 'dealing with things practically rather than theoretically', ex: 'She took a pragmatic approach to the budget.' },
  { w: 'precarious', pos: 'adj.', d: 'dangerously unstable or uncertain', ex: 'The vase sat in a precarious spot on the shelf.' },
  { w: 'prevalent', pos: 'adj.', d: 'widespread in a particular area or time', ex: 'The disease was prevalent in warm climates.' },
  { w: 'proliferate', pos: 'v.', d: 'to increase rapidly in number', ex: 'Food trucks proliferated downtown.' },
  { w: 'prudent', pos: 'adj.', d: 'acting with care for the future', ex: 'It is prudent to save part of each paycheck.' },
  { w: 'refute', pos: 'v.', d: 'to prove a statement to be wrong', ex: 'The new data refute the earlier theory.' },
  { w: 'reticent', pos: 'adj.', d: 'not revealing one\'s thoughts readily', ex: 'He was reticent about his plans.' },
  { w: 'scrutinize', pos: 'v.', d: 'to examine closely', ex: 'Reviewers scrutinized every figure in the report.' },
  { w: 'skeptical', pos: 'adj.', d: 'not easily convinced; having doubts', ex: 'Scientists were skeptical of the bold claim.' },
  { w: 'substantiate', pos: 'v.', d: 'to provide evidence to support', ex: 'She could not substantiate her accusation.' },
  { w: 'superfluous', pos: 'adj.', d: 'unnecessary; more than enough', ex: 'Cut superfluous words from your essay.' },
  { w: 'taciturn', pos: 'adj.', d: 'reserved; saying little', ex: 'The taciturn farmer answered with a shrug.' },
  { w: 'temper', pos: 'v.', d: 'to moderate or soften', ex: 'She tempered her criticism with praise.' },
  { w: 'tenuous', pos: 'adj.', d: 'very weak or slight', ex: 'The link between the two events is tenuous.' },
  { w: 'undermine', pos: 'v.', d: 'to weaken gradually', ex: 'Constant interruptions undermined her confidence.' },
  { w: 'venerate', pos: 'v.', d: 'to regard with great respect', ex: 'The town venerates its founders.' },
  { w: 'wary', pos: 'adj.', d: 'cautious about possible dangers', ex: 'Hikers were wary of the icy trail.' },
  { w: 'zealous', pos: 'adj.', d: 'having great energy for a cause', ex: 'A zealous volunteer organized the whole event.' }
];
